### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by thkruz** [thkruz/the-enhanced-scheduling-tool#3]
### User Story
- **As a** user
- **I want**  to find information about the project
- **So that** I know who made it and where to get more info

### Acceptance Criteria
- [x] /about route should display the about page
- [x] it should contain information about the authors and this github repo
- [x] it should have a link in the app drawer

**Comment by tkbdsi** [comment]
I didn't actually add info about the GitHub repo itself. Wasn't sure what to add there.
