### ISSUE TITLE
User Page

### ISSUE THREAD

**Issue by tkbdsi** [thkruz/the-enhanced-scheduling-tool#37]
### User Story
- **As a** user
- **I want**  to be able to navigate to a member's page (user/:id) to see basic information about their schedule
- **So that** so that I can easily confirm member data on a case by case basis

### Acceptance Criteria
- [x] Should show first name
- [x] Should show last name
- [x] Should have a drop down menu with preferred 
- [x] Should have a section to show the current week

### Commentary
Add other helpful information here to get exactly what you want

**Comment by thkruz** [comment]
Added
