### ISSUE TITLE
View of Monthly Calendar

### ISSUE THREAD

**Issue by thkruz** [thkruz/the-enhanced-scheduling-tool#5]
### User Story
- **As a** user
- **I want**  to be able to see a full month calendar of who is assigned when on the main page ("/" route)
- **So that** I will know who is scheduled on what days

### Acceptance Criteria
- [x] It should load data from http://localhost:3001/calendar
- [x] It should be a standalone component
- [x] It should display a full month schedule
- [x] It should display the 2 days before and after the month you are viewing
- [x] It should use a map of CalendarDay components to makeup the full calendar
- [x] It should pass a Member and Date Object to the MemberDay components as a prop named member and date
~~It should pass a XXX and Date Object to the CalendarDay components as a prop named XXX and date~~
- [x] It should have a download button that generates a csv file based on the current calendar

### Commentary
Reference google calendar as an example of what a calendar looks like:
https://calendar.google.com/

**Comment by filmo003** [comment]
Working on getting calendar to render member day components within the /user/:id pages.

**Comment by filmo003** [comment]
utilize slice in the data.map to define scope of days displayed
