### ISSUE TITLE
Create Header Component

### ISSUE THREAD

**Issue by thkruz** [thkruz/the-enhanced-scheduling-tool#8]
### User Story
- **As a** user
- **I want**  to know which page I am currently interacting with
- **So that** I don't get confused on where I am at in the app

### Acceptance Criteria
- [x] There should be a clearly defined header that is visually different than the rest of the page
- [x] The header should be a standalone component that renders on every view/route
- [x] The title of the current page should be on the header
- [x] The title of the page should change depending on which route you are using
  - [x] Viewing the main route should show 'Scheduling App'
  - [x] Viewing the admin route should show 'Admin Page'
  - [x] Viewing the users:id route should show 'Member Availability'
  - [x] Viewing the about route should show 'Developer Info'

**Comment by tkbdsi** [comment]
I've opened this back up and given it back to Collin. When Ted updated us to the slick new layout, the Header component stopped displaying which page we were on at the top within the Header.

**Comment by filmo003** [comment]
Need to review how it handles "user" pages
